kuka:
  # CONTROLLERS USED IN THE EXAMLE
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint0_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_0_joint
    pid: {p: 100,  i: 0.01, d: 10}

  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_1_joint
    pid: {p: 100,  i: 0.01, d: 10}

  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_2_joint
    pid: {p: 100,  i: 0.01, d: 10}

  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_3_joint
    pid: {p: 100,  i: 0.01, d: 10}

  joint4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_4_joint
    pid: {p: 100,  i: 0.01, d: 10}

  joint5_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_5_joint
    pid: {p: 100,  i: 0.01, d: 10}

  joint6_effort_controller:
    type: effort_controllers/JointEffortController
    joint: kuka_6_joint
    pid: {p: 100,  i: 0.01, d: 10}

  kuka_left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: kuka_left_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}

  kuka_right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: kuka_right_finger_joint
    pid: {p: 500.0, i: 0, d: 0.0}

  
